# ==================================================================================================
# Thundercast - sops operations (encrypt / updatekeys / health / operator)
# ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# Date:          Created: 2026-08-19 | Modified: 2026-08-20
# Description:   Private keys stay on the toolkit VM. Git only gets ciphertext + pubs.
# ==================================================================================================

tcast_sops_cmd() {
    command -v sops >/dev/null || tcast_die "sops not in PATH"
}

# Description: Resolve a scope to a secrets/ relative path.
# Arguments: scope-id, optional hostname (required for type=host)
tcast_sops_scope_path() {
    local id="$1" host="${2:-}" typ tmpl path
    typ="$(tcast_register_scope_get "$id" type 2>/dev/null || echo group)"
    if [[ "$typ" == "host" ]]; then
        [[ -n "$host" ]] || return 1
        tmpl="$(tcast_register_scope_get "$id" path_template 2>/dev/null || echo 'secrets/hosts/%s.yaml')"
        # shellcheck disable=SC2059
        printf "$tmpl\n" "$host"
        return 0
    fi
    path="$(tcast_register_scope_get "$id" path 2>/dev/null || true)"
    [[ -n "$path" ]] || return 1
    printf '%s\n' "$path"
}

tcast_sops_expand_member() {
    local token="$1" pub
    case "$token" in
        operator)
            pub="$(tcast_register_meta_get operator_age_pub 2>/dev/null || true)"
            [[ "$pub" == age1* ]] && printf '%s\n' "$pub"
            ;;
        age1*)
            printf '%s\n' "$token"
            ;;
        *)
            pub="$(tcast_register_host_get "$token" age_pub 2>/dev/null || true)"
            [[ "$pub" == age1* ]] && printf '%s\n' "$pub"
            ;;
    esac
}

# Description: Rewrite leaf .sops.yaml from the register (pubs only).
tcast_sops_write_policy() {
    local leaf yaml id typ path regex host pub members tmp
    tcast_register_ensure_defaults
    leaf="$(tcast_leaf)"
    yaml="${leaf}/.sops.yaml"
    tmp="$(mktemp)"
    {
        echo "# Generated by toolkit from .nds/toolkit-register (public age keys only)."
        echo "creation_rules:"
        while IFS= read -r id; do
            [[ -n "$id" ]] || continue
            typ="$(tcast_register_scope_get "$id" type 2>/dev/null || echo group)"
            if [[ "$typ" == "host" ]]; then
                while IFS= read -r host; do
                    [[ -n "$host" ]] || continue
                    pub="$(tcast_register_host_get "$host" age_pub 2>/dev/null || true)"
                    [[ "$pub" == age1* ]] || continue
                    path="$(tcast_sops_scope_path host "$host")"
                    regex="$(printf '%s' "$path" | sed 's/\./\\./g')\$"
                    echo "  - path_regex: ${regex}"
                    echo "    age:"
                    tcast_sops_expand_member operator | sed 's/^/      - /'
                    echo "      - ${pub}"
                done < <(tcast_register_host_list)
                regex="$(tcast_register_scope_get "$id" path_regex 2>/dev/null || true)"
                if [[ -n "$regex" ]]; then
                    echo "  - path_regex: ${regex}"
                    echo "    age:"
                    tcast_sops_expand_member operator | sed 's/^/      - /'
                fi
                continue
            fi
            path="$(tcast_register_scope_get "$id" path 2>/dev/null || true)"
            regex="$(tcast_register_scope_get "$id" path_regex 2>/dev/null || true)"
            if [[ -z "$regex" && -n "$path" ]]; then
                regex="$(printf '%s' "$path" | sed 's/\./\\./g')\$"
            fi
            [[ -n "$regex" ]] || continue
            echo "  - path_regex: ${regex}"
            echo "    age:"
            members="$(tcast_register_scope_get "$id" members 2>/dev/null || true)"
            if [[ -z "$members" ]]; then
                tcast_sops_expand_member operator | sed 's/^/      - /'
            else
                while IFS= read -r m; do
                    tcast_sops_expand_member "$m" | sed 's/^/      - /'
                done < <(printf '%s\n' "$members" | tr ',' '\n' | sed '/^$/d')
            fi
        done < <(tcast_register_scope_list)
    } > "$tmp"
    grep -q 'age1' "$tmp" || { rm -f "$tmp"; tcast_die "refusing to write .sops.yaml with no age recipients"; }
    mkdir -p "$(dirname "$yaml")"
    mv "$tmp" "$yaml"
}

tcast_sops_encrypt_file() {
    local rel="$1" leaf
    tcast_sops_cmd
    tcast_operator_require
    leaf="$(tcast_leaf)"
    (cd "$leaf" && sops --encrypt --in-place "$rel")
}

tcast_sops_updatekeys_file() {
    local rel="$1" leaf
    tcast_sops_cmd
    tcast_operator_require
    leaf="$(tcast_leaf)"
    (cd "$leaf" && sops updatekeys --yes "$rel")
}

tcast_sops_secret_files() {
    local leaf
    leaf="$(tcast_leaf)"
    find "${leaf}/secrets" -type f \( -name '*.yaml' -o -name '*.yml' \) ! -name 'README.md' 2>/dev/null | sort
}

tcast_sops_is_encrypted() {
    grep -q '^sops:' "$1" 2>/dev/null
}

tcast_sops_looks_private() {
    grep -qE 'AGE-SECRET-KEY-|BEGIN OPENSSH PRIVATE KEY|BEGIN RSA PRIVATE KEY|BEGIN EC PRIVATE KEY' "$1" 2>/dev/null
}

# Description: Add or replace a yaml key and encrypt at the real path (path_regex).
tcast_sops_put_value() {
    local rel="$1" key="$2" value="$3" leaf dest
    leaf="$(tcast_leaf)"
    dest="${leaf}/${rel}"
    mkdir -p "$(dirname "$dest")"
    if [[ -f "$dest" ]] && tcast_sops_is_encrypted "$dest"; then
        tcast_operator_require
        tcast_sops_cmd
        (cd "$leaf" && sops set "$rel" "[\"${key}\"]" "\"${value}\"")
    else
        printf '%s: %s\n' "$key" "$value" > "$dest"
        tcast_sops_write_policy
        tcast_sops_encrypt_file "$rel"
    fi
    tcast_register_meta_set last_secret_value_at "$(tcast_now)"
}

tcast_sops_remove_file() {
    local rel="$1" leaf dest
    leaf="$(tcast_leaf)"
    dest="${leaf}/${rel}"
    [[ -f "$dest" ]] || return 1
    rm -f "$dest"
    tcast_register_meta_set last_secret_value_at "$(tcast_now)"
}

tcast_sops_apply_recipients() {
    local leaf rel
    tcast_sops_write_policy
    leaf="$(tcast_leaf)"
    tcast_sops_cmd
    tcast_operator_require
    while IFS= read -r f; do
        [[ -n "$f" ]] || continue
        tcast_sops_is_encrypted "$f" || continue
        rel="${f#${leaf}/}"
        tcast_sops_updatekeys_file "$rel" || tcast_info "updatekeys skipped: ${rel}"
    done < <(tcast_sops_secret_files)
    tcast_register_meta_set last_recipients_at "$(tcast_now)"
}

tcast_sops_health() {
    local leaf f bad=0 enc=0 plain=0 n=0
    leaf="$(tcast_leaf)"
    n="$(tcast_sops_secret_files | grep -c . || true)"
    if ! tcast_operator_ready; then
        echo "operator: not registered"
        echo "secret files: ${n}"
        echo "encrypt / scopes / apply stay hidden until Sops → Operator → Init"
        return 0
    fi
    echo "operator: registered"
    if [[ ! -f "${leaf}/.sops.yaml" ]]; then
        echo "WARN: no .sops.yaml yet (Operator → Init writes it)"
    elif ! grep -q 'creation_rules' "${leaf}/.sops.yaml"; then
        echo "WARN: .sops.yaml has no creation_rules"
    fi
    if (( n == 0 )); then
        echo "secret files: none (empty — OK)"
        return 0
    fi
    while IFS= read -r f; do
        [[ -n "$f" ]] || continue
        if tcast_sops_looks_private "$f"; then
            echo "FAIL: private key material in ${f#${leaf}/}"
            bad=$((bad + 1))
            continue
        fi
        if tcast_sops_is_encrypted "$f"; then
            enc=$((enc + 1))
            if [[ -f "${TCAST_TOOLKIT_OP_KEY}" ]] && command -v sops >/dev/null; then
                export SOPS_AGE_KEY_FILE="${TCAST_TOOLKIT_OP_KEY}"
                if ! sops -d "$f" >/dev/null 2>&1; then
                    echo "FAIL: cannot decrypt ${f#${leaf}/} (not a recipient, or leaf is stale)"
                    bad=$((bad + 1))
                fi
            fi
        else
            plain=$((plain + 1))
            echo "WARN: unencrypted ${f#${leaf}/}"
        fi
    done < <(tcast_sops_secret_files)
    if hit="$(tcast_git_scan_private "$leaf" || true)"; [[ -n "$hit" ]]; then
        echo "FAIL: private key pattern in leaf git"
        echo "$hit"
        bad=$((bad + 1))
    fi
    echo "encrypted files: ${enc}"
    echo "unencrypted files: ${plain}"
    (( bad == 0 ))
}

tcast_sops_operator_init() {
    local dest pub leaf
    dest="${TCAST_TOOLKIT_OP_KEY}"
    mkdir -p "$(dirname "$dest")"
    if [[ ! -f "$dest" ]]; then
        command -v age-keygen >/dev/null || tcast_die "age-keygen not in PATH"
        age-keygen -o "$dest" 2>/dev/null || tcast_die "age-keygen failed"
        chmod 600 "$dest"
    fi
    pub="$(tcast_operator_pub_from_key)" || tcast_die "could not derive operator pubkey"
    tcast_register_ensure_defaults
    tcast_register_meta_set operator_age_pub "$pub"
    [[ -n "$(tcast_register_meta_get initialized_at 2>/dev/null || true)" ]] \
        || tcast_register_meta_set initialized_at "$(tcast_now)"
    leaf="$(tcast_leaf)"
    mkdir -p "${leaf}/.nds"
    printf '%s\n' "$pub" > "${leaf}/.nds/operator.age.pub"
    tcast_sops_write_policy
    tcast_info "operator pubkey recorded (private key stays at ${dest})"
}

tcast_sops_operator_rotate() {
    local dest new tmp pub old
    dest="${TCAST_TOOLKIT_OP_KEY}"
    [[ -f "$dest" ]] || tcast_die "init operator before rotate"
    command -v age-keygen >/dev/null || tcast_die "age-keygen not in PATH"
    new="$(mktemp)"
    rm -f "$new"
    age-keygen -o "$new" 2>/dev/null || tcast_die "age-keygen failed"
    tmp="$(mktemp)"
    cat "$dest" "$new" > "$tmp"
    chmod 600 "$tmp"
    export SOPS_AGE_KEY_FILE="$tmp"
    pub="$(age-keygen -y "$new" 2>/dev/null)"
    tcast_register_meta_set operator_age_pub "$pub"
    tcast_register_meta_set last_rotated_at "$(tcast_now)"
    tcast_sops_apply_recipients
    chmod 600 "$new"
    mv "$new" "$dest"
    rm -f "$tmp"
    export SOPS_AGE_KEY_FILE="$dest"
    mkdir -p "$(tcast_leaf)/.nds"
    printf '%s\n' "$pub" > "$(tcast_leaf)/.nds/operator.age.pub"
    tcast_info "operator key rotated — keep the old private until nodes have comin'd"
}

# Description: Non-interactive sops CLI (tc-sops / toolkit sops).
tcast_sops_cli() {
    local cmd="${1:-health}"
    shift || true
    case "$cmd" in
        -h|--help|help)
            cat <<'EOF'
tc-sops — encrypt / health / operator (paths relative to the toolkit leaf)

  tc-sops health
  tc-sops init
  tc-sops rotate
  tc-sops apply
  tc-sops encrypt REL
  tc-sops updatekeys REL
  tc-sops put REL KEY VALUE
  tc-sops rm REL

Leaf: TCAST_LEAF_DIR (default /var/lib/nds-toolkit/leaf). Same as the toolkit menu.
EOF
            ;;
        health) tcast_sops_health ;;
        init) tcast_sops_operator_init ;;
        rotate) tcast_sops_operator_rotate ;;
        apply) tcast_sops_apply_recipients ;;
        encrypt)
            [[ -n "${1:-}" ]] || tcast_die "usage: tc-sops encrypt REL"
            tcast_sops_encrypt_file "$1"
            ;;
        updatekeys)
            [[ -n "${1:-}" ]] || tcast_die "usage: tc-sops updatekeys REL"
            tcast_sops_updatekeys_file "$1"
            ;;
        put)
            [[ -n "${1:-}" && -n "${2:-}" && -n "${3:-}" ]] || tcast_die "usage: tc-sops put REL KEY VALUE"
            tcast_sops_put_value "$1" "$2" "$3"
            ;;
        rm|remove)
            [[ -n "${1:-}" ]] || tcast_die "usage: tc-sops rm REL"
            tcast_sops_remove_file "$1"
            ;;
        *)
            tcast_die "unknown tc-sops command: ${cmd} (try: tc-sops help)"
            ;;
    esac
}
