#!/usr/bin/env bash
# ==================================================================================================
# NDS - Install bundle quickstart markdown
# ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# Date:          Created: 2026-06-30 | Modified: 2026-08-16
# ==================================================================================================

# Description: NDS version that produced this bundle.
# Returns:
# - <String> semver or "unknown"
_nds_bundle_nds_version() {
    local ver="${SCRIPT_VERSION:-}"

    if [[ -z "$ver" && -n "${APP_DIR:-}" && -f "${APP_DIR}/VERSION" ]]; then
        ver=$(<"${APP_DIR}/VERSION")
    fi
    if [[ -z "$ver" && -n "${SCRIPT_DIR:-}" && -f "${SCRIPT_DIR}/app/VERSION" ]]; then
        ver=$(<"${SCRIPT_DIR}/app/VERSION")
    fi
    printf '%s\n' "${ver:-unknown}"
}

# Description: NixOS release of the installed system (not the live ISO).
# Returns:
# - <String> version string or "unknown"
_nds_bundle_os_release_version() {
    local file="$1"
    [[ -r "$file" ]] || return 1
    awk -F= '
        $1 == "PRETTY_NAME" { pretty = $2 }
        $1 == "VERSION" { version = $2 }
        $1 == "VERSION_ID" { id = $2 }
        END {
            v = (pretty != "" ? pretty : (version != "" ? version : id))
            gsub(/"/, "", v)
            print v
        }
    ' "$file"
}

_nds_bundle_nixos_version() {
    local ver=""

    if [[ -x /mnt/run/current-system/sw/bin/nixos-version ]]; then
        ver=$(/mnt/run/current-system/sw/bin/nixos-version 2>/dev/null || true)
    fi
    if [[ -z "$ver" ]]; then
        ver=$(_nds_bundle_os_release_version /mnt/etc/os-release 2>/dev/null || true)
    fi
    if [[ -z "$ver" && -x /run/current-system/sw/bin/nixos-version ]]; then
        ver=$(/run/current-system/sw/bin/nixos-version 2>/dev/null || true)
    fi
    if [[ -z "$ver" ]] && command -v nixos-version &>/dev/null; then
        ver=$(nixos-version 2>/dev/null || true)
    fi
    if [[ -z "$ver" ]]; then
        ver=$(_nds_bundle_os_release_version /etc/os-release 2>/dev/null || true)
    fi
    printf '%s\n' "${ver:-unknown}"
}

# Description: GitHub README for the action that produced this bundle.
# Returns:
# - <String> URL
_nds_bundle_action_readme_url() {
    local action="${NDS_CURRENT_ACTION:-${NDS_ACTION:-classicInstall}}"
    local slug="classicInstall"
    case "$action" in
        installFlake) slug="installFlake" ;;
        remoteAction) slug="remoteAction" ;;
        classicInstall) slug="classicInstall" ;;
    esac
    printf 'https://github.com/CodeAnthem/thundercast/blob/main/src/actions/%s/README.md\n' "$slug"
}

# Description: Write personalized quick-start markdown from NDS_CTX_* snapshot.
# Mentions secrets/admin_password.txt only when NDS actually wrote that file.
_nds_bundle_quickstart() {
    local dest="$1"
    local hostname admin_user ssh_port ssh_pw_auth admin_ssh_key port_opt host_ip
    local encryption use_password use_key key_device key_file
    local remote_unlock remote_net remote_ip remote_port unlock_ip ip_note
    local staging_dir has_admin_pw=false has_git_keys=false
    local nds_ver nixos_ver git_key

    hostname="${NDS_CTX_HOSTNAME:-unknown}"
    admin_user="${NDS_CTX_ADMIN_USER:-admin}"
    ssh_port="${NDS_CTX_SSH_PORT:-22}"
    ssh_pw_auth="${NDS_CTX_SSH_PW_AUTH:-true}"
    admin_ssh_key="${NDS_CTX_ADMIN_SSH_KEY:-}"
    encryption="${NDS_CTX_ENCRYPTION:-}"
    use_password="${NDS_CTX_ENCRYPTION_PASSWORD:-}"
    use_key="${NDS_CTX_ENCRYPTION_KEY:-}"
    key_device="${NDS_CTX_KEY_BOOT_DEVICE:-}"
    key_file="${NDS_CTX_KEY_BOOT_FILE:-}"
    remote_unlock="${NDS_CTX_REMOTE_UNLOCK:-}"
    remote_net="${NDS_CTX_REMOTE_NETWORK:-}"
    remote_ip="${NDS_CTX_NETWORK_IP:-}"
    remote_port="${NDS_CTX_REMOTE_PORT:-2222}"

    staging_dir="$(dirname "$dest")"
    if [[ -f "${staging_dir}/secrets/admin_password.txt" ]] \
        || [[ -f "${NDS_RUNTIME_DIR:-}/secrets/admin_password.txt" ]]; then
        has_admin_pw=true
    fi
    if [[ -d "${staging_dir}/secrets/git" ]]; then
        for git_key in "${staging_dir}/secrets/git"/*; do
            if [[ -f "$git_key" ]]; then
                has_git_keys=true
                break
            fi
        done
    fi

    # The address this install was reached on - the booted machine gets the same
    # DHCP lease (MAC-based client id), so this is the address to connect to.
    host_ip=$(nds_lib_getHostIP 2>/dev/null || true)
    [[ -z "$host_ip" ]] && host_ip="<machine-ip>"

    port_opt=""
    [[ -n "$ssh_port" && "$ssh_port" != "22" ]] && port_opt=" -p ${ssh_port}"

    nds_ver=$(_nds_bundle_nds_version)
    nixos_ver=$(_nds_bundle_nixos_version)

    {
        cat <<EOF
# NDS Quick Start - ${hostname}

Personalized setup guide for this machine, generated by the Nix Deploy System at install
time. **Keep this bundle safe** - it also holds unlock secrets when encryption was used.

- **Hostname:** ${hostname}
- **Address:** ${host_ip}
- **NDS version:** ${nds_ver}
- **NixOS version:** ${nixos_ver}
- **Created:** $(date -Iseconds 2>/dev/null || date)

## What's in this bundle

| Path | What |
|------|------|
| \`nds-restore.env\` | Settings + runtime exports, then curl. Paste all, or copy the export blocks. |
| \`config/*\` | Generated artifacts (e.g. facter.json, classic configuration.nix) |
| \`logs/nds.log\` | NDS session, install steps, and diagnostics (no nixos-install dump) |
| \`logs/nixosInstallation.log\` | Output of \`nixos-install\` / flake build / nixos-anywhere only |
EOF

        if [[ "$has_admin_pw" == "true" ]]; then
            printf '| `secrets/admin_password.txt` | Admin user initial password - **save this** |\n'
        fi

        if [[ "$encryption" == "true" ]]; then
            [[ "$use_password" == "true" ]] && printf '| `secrets/luks_password.txt` | LUKS passphrase - **save this** |\n'
            [[ "$use_key" == "true" ]] && printf '| `secrets/luks_key.bin` | LUKS keyfile - copy to your USB (see below) |\n'
            [[ "$remote_unlock" == "true" ]] && printf '| `secrets/initrd_ssh_host_ed25519_key[.pub]` | Initrd SSH **host** key (the machine identity, not your login key) |\n'
        fi

        if [[ "$has_git_keys" == "true" ]]; then
            printf '| `secrets/git/*` | Private SSH keys used for flake git access. Copy to `/root/.ssh/` (chmod 600) before pasting nds-restore.env. |\n'
        fi

        if [[ "$encryption" == "true" && "$remote_unlock" == "true" ]]; then
            unlock_ip="$host_ip"
            ip_note="DHCP uses a MAC-based client id, so the initrd gets the **same** address as the booted machine (below). If your DHCP server reassigns, check its logs for the lease shown while the LUKS prompt is up."
            if [[ "$remote_net" == "static" && -n "$remote_ip" ]]; then
                unlock_ip="${remote_ip%/*}"
                ip_note="Static IP configured - always reachable at the address below."
            fi

            cat <<EOF

## Remote unlock (initrd SSH)

Unlock the disk **before** you can log in. A tiny SSH server runs in the initrd
until LUKS is opened.

- Listens on **port ${remote_port}** as user **root**, pubkey-only (not the booted SSH on port 22).
- ${ip_note}
- **Passphrase:** \`secrets/luks_password.txt\` (typed at the SSH prompt, or at the VM console).

Use the **private key that matches the public key you pasted during install**.
That private key stays on your PC - it is not in this zip.
\`-o IdentitiesOnly=yes\` makes ssh use only the key you pass with \`-i\`.

\`\`\`bash
ssh -p ${remote_port} -i /path/to/your-unlock-private-key -o IdentitiesOnly=yes root@${unlock_ip}
\`\`\`

If you stored it as \`~/.ssh/nixos-unlock\` (the name in the install docs):

\`\`\`bash
ssh -p ${remote_port} -i ~/.ssh/nixos-unlock -o IdentitiesOnly=yes root@${unlock_ip}
\`\`\`

The LUKS prompt appears as soon as you connect; type the passphrase and the machine boots.

### Initrd host key vs your unlock key

| File | Who | What it does |
|------|-----|----------------|
| \`secrets/initrd_ssh_host_ed25519_key\` | This machine | SSH **host** key for the initrd server. Your client uses it like any host key (\`known_hosts\`). Do **not** pass it as \`ssh -i\`. |
| (not in this zip) | You | Unlock **client** key. Only the public half was installed. If you lost the private half, unlock at the console with the LUKS passphrase. |

Do not generate a new unlock key from this guide - a new key would not be authorized on this machine.
EOF
        fi

        if [[ "$encryption" == "true" && "$remote_unlock" != "true" ]]; then
            cat <<EOF

## Disk encryption (LUKS)

This machine's root disk is encrypted - it must be unlocked at every boot.
EOF
            [[ "$use_password" == "true" ]] && \
                printf '\n- **Passphrase:** in `secrets/luks_password.txt`. Type it at the boot/console prompt.\n'
        fi

        if [[ "$encryption" == "true" && "$use_key" == "true" ]]; then
            cat <<EOF

### USB keyfile (required to boot)

The keyfile is in this bundle at \`secrets/luks_key.bin\`. It is **never** written to the
target disk - stage it on a USB stick yourself and plug that USB in at every boot. Its
device path must match:

    ENCRYPTION_KEY_BOOT_DEVICE = ${key_device}
EOF
            if [[ -z "$key_file" ]]; then
                cat <<EOF

Copy it as **raw bytes** to the USB device (do this BEFORE rebooting):

\`\`\`bash
dd if=secrets/luks_key.bin of=<usb-device> bs=4096 count=1
\`\`\`
EOF
            else
                cat <<EOF

Copy it as a **file** onto a mounted USB stick (do this BEFORE rebooting):

\`\`\`bash
mount <usb-device> /mnt/usb
cp secrets/luks_key.bin /mnt/usb/${key_file}
umount /mnt/usb
\`\`\`
EOF
            fi

            [[ "$use_password" != "true" ]] && cat <<EOF

> **WARNING - key-only mode (no passphrase).** If this USB is lost, stolen, or corrupted,
> the system **cannot** boot. There is no fallback.
EOF
        fi

        cat <<EOF

## First login

EOF
        if [[ "$has_admin_pw" == "true" ]]; then
            cat <<EOF
- **Console:** log in as \`${admin_user}\` with the password in \`secrets/admin_password.txt\`.
EOF
            if [[ "$ssh_pw_auth" == "true" || -z "$admin_ssh_key" ]]; then
                cat <<EOF
- **SSH from your PC:**

  \`\`\`bash
  ssh ${admin_user}@${host_ip}${port_opt}
  \`\`\`

  Password login is enabled - use the password above.
EOF
            else
                cat <<EOF
- **SSH from your PC** (key-only - password login is off, use your key):

  \`\`\`bash
  ssh -i <your-private-key> ${admin_user}@${host_ip}${port_opt}
  \`\`\`
EOF
            fi
            cat <<EOF

Change the admin password after first login:

\`\`\`bash
passwd
\`\`\`
EOF
        else
            cat <<EOF
NDS did **not** set a login password for this install (typical for \`installFlake\`).
Use the credentials defined in your flake (user / password / SSH keys).

- **SSH example** (adjust user to match the flake):

  \`\`\`bash
  ssh root@${host_ip}${port_opt}
  \`\`\`
EOF
        fi

        if [[ "$has_git_keys" == "true" ]]; then
            cat <<EOF

## Recreate this install (private git)

This zip includes the SSH keys NDS used to fetch private flakes. Copy them onto the live
ISO before pasting \`nds-restore.env\` (\`NDS_GIT_KEY_PATH\` already points at \`/root/.ssh/<filename>\`):

\`\`\`bash
mkdir -p /root/.ssh
cp secrets/git/* /root/.ssh/
chmod 600 /root/.ssh/*
chmod 644 /root/.ssh/*.pub 2>/dev/null || true
\`\`\`
EOF
        fi

        cat <<EOF

---

Online docs: https://github.com/CodeAnthem/thundercast
Install guide: $(_nds_bundle_action_readme_url)
Remote unlock guide: https://github.com/CodeAnthem/thundercast/blob/main/docs/remote-unlock.md
EOF
    } > "$dest"
}
